name: Documentation
description: Report issues or suggest improvements for documentation
title: "[Docs]: "
labels: ["documentation", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! 📚
        
        Clear documentation helps everyone in the community.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs attention?
      options:
        - README
        - API Documentation
        - Code Comments
        - Tutorial/Guide
        - Setup/Installation Instructions
        - Contributing Guidelines
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Documentation Issue
      description: Describe the issue or what's missing/unclear
      placeholder: The current documentation says... but it should...
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is this documentation located?
      placeholder: |
        - File: README.md
        - Section: Installation
        - Line numbers: 45-60
        - URL: https://...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you improve this documentation?
      placeholder: I suggest changing/adding...
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples/References
      description: Provide examples or references to similar good documentation
      placeholder: For example, see how X project documents this...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the documentation issue
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues about documentation
          required: true
        - label: I have checked the latest version of the documentation
          required: true
        - label: I am willing to help improve this documentation if guidance is provided
          required: false
