name: Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! 🤔
        
        Before asking, please check:
        - The project README
        - Existing issues and discussions
        - Documentation and guides
        
        If you still need help, we're here!

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...? / Why does... / What is the best way to...?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about what you're trying to do
      placeholder: |
        I'm trying to...
        I want to achieve...
        My use case is...
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: What Have You Tried?
      description: What approaches have you already attempted?
      placeholder: |
        I tried...
        I looked at...
        I read...
    validations:
      required: false

  - type: textarea
    id: code
    attributes:
      label: Relevant Code/Configuration
      description: Share any relevant code or configuration
      placeholder: |
        ```python
        # Your code here
        ```
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: Information about your environment
      placeholder: |
        - OS: [e.g., macOS, Ubuntu, Windows]
        - Version: [e.g., v1.0.0]
        - Language version: [e.g., Python 3.11]
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have checked the documentation
          required: true
        - label: This is not a bug report (for bugs, use the Bug Report template)
          required: true
